---
- name: "Start the filter_band config!"
  hosts: AP-17.local
  tasks:
    - name: "Copy Files onto the server"
      ansible.builtin.copy:
        src: SC
        dest: /home/member/Desktop/Filter_Band
        owner: member
        group: member
        mode: "0644"

    - name: "Launch SC!"
      async: 2592000 # run for 1 month
      poll: 0
      shell: DISPLAY=:0 sclang filter_gui.scd
      args:
        chdir: /home/member/Desktop/Filter_Band/SC

    - name: "Launch JackTrip!"
      shell: jacktrip -s
      async: 2592000 # run for 1 month
      poll: 0
