---
- name: "Start the piece neighbour phaser"
  hosts: really_active_sprawl_nodes
  gather_facts: true
  tasks:
    - name: "Jack Connect"
      shell: |
        jack_connect SuperCollider:out_1 system:playback_1
        jack_connect system:capture_1 SuperCollider:in_1
